"""Registra todos los modelos en Base.metadata (lo necesita Alembic)."""

from app.models.admin import AdminRole, AdminSession, AdminUser
from app.models.booking import (
    Booking,
    BookingItem,
    BookingLeg,
    BookingSource,
    BookingStatus,
    BookingType,
    ItemType,
    LegStatus,
    LegType,
)
from app.models.catalog import (
    Activity,
    ActivityPackage,
    DiscountType,
    Extra,
    ExtraAutoRule,
    Hotel,
    PricingMode,
    Promotion,
    PromotionScope,
    Rate,
    ServiceScope,
    TripType,
    VehicleClass,
    Zone,
)
from app.models.communication import (
    AiConversation,
    AiMessage,
    ContactMessage,
    ContactStatus,
    ConversationStatus,
    EmailOutbox,
    EmailStatus,
    MessageRole,
    Review,
    ReviewSource,
)
from app.models.company import Company, CompanySettings
from app.models.customer import Customer
from app.models.finance import (
    AccountCharge,
    AccountPayment,
    AccountPaymentMethod,
    AccountStatus,
    ChargeStatus,
    ClientAccount,
    Payment,
    PaymentProvider,
    PaymentStatus,
    StripeEvent,
)
from app.models.operations import (
    AdminTask,
    AuditActor,
    AuditLog,
    BookingAssignment,
    Driver,
    TaskCategory,
    TaskStatus,
    Vehicle,
)
from app.models.sequences import BookingCodeCounter

__all__ = [
    "AccountCharge",
    "AccountPayment",
    "AccountPaymentMethod",
    "AccountStatus",
    "Activity",
    "ActivityPackage",
    "AdminRole",
    "AdminSession",
    "AdminTask",
    "AdminUser",
    "AiConversation",
    "AiMessage",
    "AuditActor",
    "AuditLog",
    "Booking",
    "BookingAssignment",
    "BookingCodeCounter",
    "BookingItem",
    "BookingLeg",
    "BookingSource",
    "BookingStatus",
    "BookingType",
    "ChargeStatus",
    "ClientAccount",
    "Company",
    "CompanySettings",
    "ContactMessage",
    "ContactStatus",
    "ConversationStatus",
    "Customer",
    "DiscountType",
    "Driver",
    "EmailOutbox",
    "EmailStatus",
    "Extra",
    "ExtraAutoRule",
    "Hotel",
    "ItemType",
    "LegStatus",
    "LegType",
    "MessageRole",
    "Payment",
    "PaymentProvider",
    "PaymentStatus",
    "PricingMode",
    "Promotion",
    "PromotionScope",
    "Rate",
    "Review",
    "ReviewSource",
    "ServiceScope",
    "StripeEvent",
    "TaskCategory",
    "TaskStatus",
    "TripType",
    "Vehicle",
    "VehicleClass",
    "Zone",
]
