"""Registra todos los modelos en Base.metadata (lo necesita Alembic)."""

from app.models.admin import AdminRole, AdminSession, AdminUser
from app.models.booking import (
    Booking,
    BookingItem,
    BookingLeg,
    BookingSource,
    BookingStatus,
    BookingType,
    ItemType,
    LegStatus,
    LegType,
)
from app.models.catalog import (
    Activity,
    ActivityPackage,
    DiscountType,
    Extra,
    ExtraAutoRule,
    Hotel,
    PricingMode,
    Promotion,
    PromotionScope,
    Rate,
    ServiceScope,
    TripType,
    VehicleClass,
    Zone,
)
from app.models.company import Company, CompanySettings
from app.models.customer import Customer
from app.models.finance import (
    AccountCharge,
    AccountPayment,
    AccountPaymentMethod,
    AccountStatus,
    ChargeStatus,
    ClientAccount,
    Payment,
    PaymentProvider,
    PaymentStatus,
    StripeEvent,
)

__all__ = [
    "AccountCharge",
    "AccountPayment",
    "AccountPaymentMethod",
    "AccountStatus",
    "Activity",
    "ActivityPackage",
    "AdminRole",
    "AdminSession",
    "AdminUser",
    "Booking",
    "BookingItem",
    "BookingLeg",
    "BookingSource",
    "BookingStatus",
    "BookingType",
    "ChargeStatus",
    "ClientAccount",
    "Company",
    "CompanySettings",
    "Customer",
    "DiscountType",
    "Extra",
    "ExtraAutoRule",
    "Hotel",
    "ItemType",
    "LegStatus",
    "LegType",
    "Payment",
    "PaymentProvider",
    "PaymentStatus",
    "PricingMode",
    "Promotion",
    "PromotionScope",
    "Rate",
    "ServiceScope",
    "StripeEvent",
    "TripType",
    "VehicleClass",
    "Zone",
]
