"""pagos y finanzas

Revision ID: 56ed3ca7c373
Revises: 0b3217285efc
Create Date: 2026-09-12 17:24:37.405725
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "56ed3ca7c373"
down_revision: str | None = "0b3217285efc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_events",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stripe_events")),
    )
    op.create_table(
        "client_accounts",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "on_hold",
                "settled",
                "closed",
                name="accountstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("credit_limit_cents", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("credit_limit_cents >= 0", name=op.f("ck_client_accounts_credit_limit")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_client_accounts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_client_accounts_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_accounts")),
    )
    op.create_index(
        op.f("ix_client_accounts_customer_id"), "client_accounts", ["customer_id"], unique=False
    )
    op.create_table(
        "account_charges",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "invoiced",
                "paid",
                "void",
                name="chargestatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_account_charges_amount_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["client_accounts.id"],
            name=op.f("fk_account_charges_account_id_client_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_account_charges_booking_id_bookings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_account_charges_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_charges")),
    )
    op.create_index(
        op.f("ix_account_charges_account_id"), "account_charges", ["account_id"], unique=False
    )
    op.create_table(
        "account_payments",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "cash",
                "bank_transfer",
                "card",
                "manual",
                name="accountpaymentmethod",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("received_by_admin_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_account_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["client_accounts.id"],
            name=op.f("fk_account_payments_account_id_client_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_account_payments_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["received_by_admin_id"],
            ["admin_users.id"],
            name=op.f("fk_account_payments_received_by_admin_id_admin_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_payments")),
    )
    op.create_index(
        op.f("ix_account_payments_account_id"), "account_payments", ["account_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "stripe",
                "cash",
                "bank_transfer",
                "account",
                "manual",
                name="paymentprovider",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "succeeded",
                "failed",
                "refunded",
                "partially_refunded",
                "cancelled",
                name="paymentstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("refunded_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("stripe_payment_intent_id", sa.String(length=64), nullable=True),
        sa.Column("stripe_checkout_session_id", sa.String(length=80), nullable=True),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("received_by_admin_id", sa.Uuid(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_cents > 0 AND refunded_cents >= 0 AND refunded_cents <= amount_cents",
            name=op.f("ck_payments_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_payments_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payments_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["received_by_admin_id"],
            ["admin_users.id"],
            name=op.f("fk_payments_received_by_admin_id_admin_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint(
            "stripe_checkout_session_id", name=op.f("uq_payments_stripe_checkout_session_id")
        ),
        sa.UniqueConstraint(
            "stripe_payment_intent_id", name=op.f("uq_payments_stripe_payment_intent_id")
        ),
    )
    op.create_index(op.f("ix_payments_booking_id"), "payments", ["booking_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_booking_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_account_payments_account_id"), table_name="account_payments")
    op.drop_table("account_payments")
    op.drop_index(op.f("ix_account_charges_account_id"), table_name="account_charges")
    op.drop_table("account_charges")
    op.drop_index(op.f("ix_client_accounts_customer_id"), table_name="client_accounts")
    op.drop_table("client_accounts")
    op.drop_table("stripe_events")
    # ### end Alembic commands ###
