"""terminos y metodo de pago en reservas

Revision ID: 0d1e992bc78d
Revises: a669171fe543
Create Date: 2026-09-13 02:05:07.027790
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0d1e992bc78d"
down_revision: str | None = "a669171fe543"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("terms_version", sa.String(length=20), nullable=True))
    op.add_column("bookings", sa.Column("payment_method", sa.String(length=10), nullable=True))
    op.add_column(
        "company_settings",
        sa.Column("terms_version", sa.String(length=20), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_settings", "terms_version")
    op.drop_column("bookings", "payment_method")
    op.drop_column("bookings", "terms_version")
    # ### end Alembic commands ###
