"""clave de idempotencia en reservas

Revision ID: 9c5a8aed60e7
Revises: 523ec6ce4943
Create Date: 2026-09-12 20:50:58.262058
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9c5a8aed60e7"
down_revision: str | None = "523ec6ce4943"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("idempotency_key", sa.String(length=80), nullable=True))
    op.create_index(
        "uq_bookings_company_idempotency_key",
        "bookings",
        ["company_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_bookings_company_idempotency_key",
        table_name="bookings",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_column("bookings", "idempotency_key")
    # ### end Alembic commands ###
