"""catalogo y clientes

Revision ID: 4b96b66d17b0
Revises: 5721f5faa1c7
Create Date: 2026-09-12 17:16:49.431464
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4b96b66d17b0"
down_revision: str | None = "5721f5faa1c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Búsqueda de hoteles por similitud (ix_hotels_name_trgm). Se agrega a mano: autogenerate no crea extensiones.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_activities_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
        sa.UniqueConstraint("company_id", "slug", name=op.f("uq_activities_company_id_slug")),
    )
    op.create_table(
        "activity_packages",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("activity_count", sa.Integer(), nullable=False),
        sa.Column("price_per_person_cents", sa.Integer(), nullable=False),
        sa.Column("park_fee_cents", sa.Integer(), nullable=False),
        sa.Column("deposit_cents", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activity_count >= 1 AND price_per_person_cents >= 0 AND park_fee_cents >= 0 AND deposit_cents >= 0",
            name=op.f("ck_activity_packages_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_activity_packages_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_packages")),
        sa.UniqueConstraint(
            "company_id", "slug", name=op.f("uq_activity_packages_company_id_slug")
        ),
    )
    op.create_table(
        "customers",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("marketing_opt_in", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_customers_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(
        "uq_customers_company_email",
        "customers",
        ["company_id", sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_table(
        "extras",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column(
            "pricing_mode",
            sa.Enum(
                "per_booking",
                "per_stop",
                "per_seat",
                "per_hour",
                name="pricingmode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("max_qty", sa.Integer(), nullable=False),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.Column(
            "auto_rule",
            sa.Enum(
                "night_surcharge",
                name="extraautorule",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price_cents >= 0 AND max_qty >= 1", name=op.f("ck_extras_price_and_qty")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_extras_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extras")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_extras_company_id_code")),
    )
    op.create_table(
        "promotions",
        sa.Column("code", sa.String(length=40), nullable=True),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "discount_type",
            sa.Enum(
                "percent",
                "fixed",
                name="discounttype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column(
            "applies_to",
            sa.Enum(
                "transfer_base",
                "all",
                name="promotionscope",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("travel_from", sa.Date(), nullable=True),
        sa.Column("travel_to", sa.Date(), nullable=True),
        sa.Column("book_from", sa.Date(), nullable=True),
        sa.Column("book_to", sa.Date(), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value > 0 AND (discount_type <> 'percent' OR value <= 100)",
            name=op.f("ck_promotions_valid_value"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_promotions_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotions")),
    )
    op.create_index(
        "uq_promotions_company_code",
        "promotions",
        ["company_id", sa.literal_column("lower(code)")],
        unique=True,
        postgresql_where=sa.text("code IS NOT NULL"),
    )
    op.create_table(
        "vehicle_classes",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("min_pax", sa.Integer(), nullable=False),
        sa.Column("max_pax", sa.Integer(), nullable=False),
        sa.Column("max_bags", sa.Integer(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "min_pax >= 1 AND max_pax >= min_pax", name=op.f("ck_vehicle_classes_pax_range")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vehicle_classes_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_classes")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_vehicle_classes_company_id_code")),
    )
    op.create_table(
        "zones",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("drive_minutes_min", sa.Integer(), nullable=False),
        sa.Column("drive_minutes_max", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_zones_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zones")),
        sa.UniqueConstraint("company_id", "slug", name=op.f("uq_zones_company_id_slug")),
    )
    op.create_table(
        "hotels",
        sa.Column("zone_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.String(length=160)), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_hotels_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name=op.f("fk_hotels_zone_id_zones"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotels")),
        sa.UniqueConstraint("company_id", "slug", name=op.f("uq_hotels_company_id_slug")),
    )
    op.create_index(
        "ix_hotels_name_trgm",
        "hotels",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_hotels_zone_id"), "hotels", ["zone_id"], unique=False)
    op.create_table(
        "rates",
        sa.Column("zone_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_class_id", sa.Uuid(), nullable=False),
        sa.Column(
            "trip_type",
            sa.Enum(
                "one_way",
                "round_trip",
                name="triptype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "service_scope",
            sa.Enum(
                "airport",
                "local",
                name="servicescope",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price_cents >= 0", name=op.f("ck_rates_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_rates_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_class_id"],
            ["vehicle_classes.id"],
            name=op.f("fk_rates_vehicle_class_id_vehicle_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name=op.f("fk_rates_zone_id_zones"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rates")),
        sa.UniqueConstraint(
            "company_id",
            "zone_id",
            "vehicle_class_id",
            "trip_type",
            "service_scope",
            name="uq_rates_zone_vehicle_trip_scope",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rates")
    op.drop_index(op.f("ix_hotels_zone_id"), table_name="hotels")
    op.drop_index(
        "ix_hotels_name_trgm",
        table_name="hotels",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("hotels")
    op.drop_table("zones")
    op.drop_table("vehicle_classes")
    op.drop_index(
        "uq_promotions_company_code",
        table_name="promotions",
        postgresql_where=sa.text("code IS NOT NULL"),
    )
    op.drop_table("promotions")
    op.drop_table("extras")
    op.drop_index("uq_customers_company_email", table_name="customers")
    op.drop_table("customers")
    op.drop_table("activity_packages")
    op.drop_table("activities")
    # ### end Alembic commands ###
