"""contador de codigos de reserva

Revision ID: 523ec6ce4943
Revises: a6a95d459beb
Create Date: 2026-09-12 17:40:57.949826
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "523ec6ce4943"
down_revision: str | None = "a6a95d459beb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking_code_counters",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.CheckConstraint("last_value >= 1", name=op.f("ck_booking_code_counters_last_value")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_booking_code_counters_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("company_id", "year", name=op.f("pk_booking_code_counters")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("booking_code_counters")
    # ### end Alembic commands ###
