"""codigos_de_respaldo_totp_del_admin

Revision ID: 9d88d124a402
Revises: 0e5b48905a6c
Create Date: 2026-09-13 02:49:19.249457
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9d88d124a402"
down_revision: str | None = "0e5b48905a6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_users",
        sa.Column(
            "totp_backup_codes",
            postgresql.ARRAY(sa.String(length=64)),
            nullable=False,
            server_default="{}",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admin_users", "totp_backup_codes")
    # ### end Alembic commands ###
