"""reservas

Revision ID: 0b3217285efc
Revises: 4b96b66d17b0
Create Date: 2026-09-12 17:21:09.081508
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0b3217285efc"
down_revision: str | None = "4b96b66d17b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_payment",
                "offline_hold",
                "confirmed",
                "paid",
                "completed",
                "cancelled",
                name="bookingstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "website",
                "admin",
                "ai_chat",
                "whatsapp",
                "phone",
                name="bookingsource",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "booking_type",
            sa.Enum(
                "transfer",
                "activity",
                "mixed",
                name="bookingtype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), nullable=False),
        sa.Column("discount_cents", sa.Integer(), nullable=False),
        sa.Column("tax_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("promotion_id", sa.Uuid(), nullable=True),
        sa.Column("notes_customer", sa.Text(), nullable=True),
        sa.Column("notes_internal", sa.Text(), nullable=True),
        sa.Column("created_by_admin_id", sa.Uuid(), nullable=True),
        sa.Column("utm", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=300), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "subtotal_cents >= 0 AND discount_cents >= 0 AND tax_cents >= 0 AND total_cents = subtotal_cents - discount_cents + tax_cents AND total_cents >= 0",
            name=op.f("ck_bookings_totals"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_bookings_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_admin_id"],
            ["admin_users.id"],
            name=op.f("fk_bookings_created_by_admin_id_admin_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_bookings_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["promotion_id"],
            ["promotions.id"],
            name=op.f("fk_bookings_promotion_id_promotions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_bookings_company_id_code")),
    )
    op.create_index(
        "ix_bookings_company_status_created",
        "bookings",
        ["company_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_bookings_customer_id"), "bookings", ["customer_id"], unique=False)
    op.create_table(
        "booking_legs",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column(
            "leg_type",
            sa.Enum(
                "arrival",
                "departure",
                "local",
                name="legtype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "completed",
                "cancelled",
                name="legstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("service_time", sa.Time(), nullable=True),
        sa.Column("pickup_time", sa.Time(), nullable=True),
        sa.Column("flight_number", sa.String(length=10), nullable=True),
        sa.Column("airline", sa.String(length=60), nullable=True),
        sa.Column("origin", sa.String(length=200), nullable=False),
        sa.Column("destination", sa.String(length=200), nullable=False),
        sa.Column("hotel_id", sa.Uuid(), nullable=True),
        sa.Column("pax_adults", sa.Integer(), nullable=False),
        sa.Column("pax_children", sa.Integer(), nullable=False),
        sa.Column("vehicle_class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pax_adults >= 1 AND pax_children >= 0", name=op.f("ck_booking_legs_pax")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_legs_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_booking_legs_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name=op.f("fk_booking_legs_hotel_id_hotels"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_class_id"],
            ["vehicle_classes.id"],
            name=op.f("fk_booking_legs_vehicle_class_id_vehicle_classes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_legs")),
    )
    op.create_index(
        op.f("ix_booking_legs_booking_id"), "booking_legs", ["booking_id"], unique=False
    )
    op.create_index(
        "ix_booking_legs_company_service_date",
        "booking_legs",
        ["company_id", "service_date"],
        unique=False,
    )
    op.create_table(
        "booking_items",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("leg_id", sa.Uuid(), nullable=True),
        sa.Column(
            "item_type",
            sa.Enum(
                "transfer",
                "extra",
                "activity",
                "park_fee",
                "discount",
                name="itemtype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("ref_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity >= 1 AND total_cents = quantity * unit_price_cents AND (item_type = 'discount' OR unit_price_cents >= 0)",
            name=op.f("ck_booking_items_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_items_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_booking_items_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["leg_id"],
            ["booking_legs.id"],
            name=op.f("fk_booking_items_leg_id_booking_legs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_items")),
    )
    op.create_index(
        op.f("ix_booking_items_booking_id"), "booking_items", ["booking_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_booking_items_booking_id"), table_name="booking_items")
    op.drop_table("booking_items")
    op.drop_index("ix_booking_legs_company_service_date", table_name="booking_legs")
    op.drop_index(op.f("ix_booking_legs_booking_id"), table_name="booking_legs")
    op.drop_table("booking_legs")
    op.drop_index(op.f("ix_bookings_customer_id"), table_name="bookings")
    op.drop_index("ix_bookings_company_status_created", table_name="bookings")
    op.drop_table("bookings")
    # ### end Alembic commands ###
