"""anticipacion minima para reservar

Revision ID: 4e2afe533f53
Revises: 9c5a8aed60e7
Create Date: 2026-09-12 20:57:40.272038
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4e2afe533f53"
down_revision: str | None = "9c5a8aed60e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_settings",
        sa.Column("min_notice_hours", sa.Integer(), server_default="24", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_settings", "min_notice_hours")
    # ### end Alembic commands ###
