"""email_del_chofer_para_avisos_de_despacho

Revision ID: a525576ffab7
Revises: 9d88d124a402
Create Date: 2026-09-14 00:33:36.287462
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a525576ffab7"
down_revision: str | None = "9d88d124a402"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drivers", sa.Column("email", sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("drivers", "email")
    # ### end Alembic commands ###
