"""tarifas y reglas de vehiculos como la referencia

Revision ID: a669171fe543
Revises: 43fcd1c0fe04
Create Date: 2026-09-12 22:33:26.609356
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a669171fe543"
down_revision: str | None = "43fcd1c0fe04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "booking_assignments",
        sa.Column("unit_index", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_constraint(op.f("uq_booking_assignments_leg_id"), "booking_assignments", type_="unique")
    op.create_unique_constraint(
        op.f("uq_booking_assignments_leg_id_unit_index"),
        "booking_assignments",
        ["leg_id", "unit_index"],
    )
    op.add_column(
        "booking_legs", sa.Column("vehicle_count", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "company_settings",
        sa.Column("card_tax_percent", sa.Integer(), server_default="16", nullable=False),
    )
    op.add_column("extras", sa.Column("free_qty", sa.Integer(), server_default="0", nullable=False))
    op.add_column(
        "extras",
        sa.Column(
            "vehicle_prices",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "extras",
        sa.Column("one_per_vehicle", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("vehicle_classes", sa.Column("included_pax", sa.Integer(), nullable=True))
    op.add_column(
        "vehicle_classes",
        sa.Column("extra_pax_cents", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "vehicle_classes",
        sa.Column("extra_hour_cents", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "vehicle_classes",
        sa.Column("cash_deposit_cents", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_classes", "cash_deposit_cents")
    op.drop_column("vehicle_classes", "extra_hour_cents")
    op.drop_column("vehicle_classes", "extra_pax_cents")
    op.drop_column("vehicle_classes", "included_pax")
    op.drop_column("extras", "one_per_vehicle")
    op.drop_column("extras", "vehicle_prices")
    op.drop_column("extras", "free_qty")
    op.drop_column("company_settings", "card_tax_percent")
    op.drop_column("booking_legs", "vehicle_count")
    op.drop_constraint(
        op.f("uq_booking_assignments_leg_id_unit_index"), "booking_assignments", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_booking_assignments_leg_id"),
        "booking_assignments",
        ["leg_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("booking_assignments", "unit_index")
    # ### end Alembic commands ###
