"""fecha de actividad en items de reserva

Revision ID: 43fcd1c0fe04
Revises: 4e2afe533f53
Create Date: 2026-09-12 21:20:40.803088
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "43fcd1c0fe04"
down_revision: str | None = "4e2afe533f53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking_items", sa.Column("service_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking_items", "service_date")
    # ### end Alembic commands ###
