/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: responde sin tocar la base de datos.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: confirma que Postgres responde en menos de 2 s.
         */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zones */
        get: operations["zones_api_v1_catalog_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/hotels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hotels */
        get: operations["hotels_api_v1_catalog_hotels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/hotels/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hotel */
        get: operations["hotel_api_v1_catalog_hotels__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vehicles */
        get: operations["vehicles_api_v1_catalog_vehicles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/extras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Extras */
        get: operations["extras_api_v1_catalog_extras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activities */
        get: operations["activities_api_v1_catalog_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Packages */
        get: operations["packages_api_v1_catalog_packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Quote
         * @description Cotización autoritativa; los errores corregibles responden 422 con `code` estable.
         */
        post: operations["create_quote_api_v1_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create
         * @description Crea la reserva en `pending_payment`; el mismo `Idempotency-Key` no la duplica.
         */
        post: operations["create_api_v1_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup
         * @description My Trip: código + email. Si no existe o el email no coincide, la respuesta es la misma.
         */
        get: operations["lookup_api_v1_bookings_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_v1_bookings__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change
         * @description Cambios permitidos por política: vuelo, aerolínea, hora del vuelo y notas.
         */
        patch: operations["change_api_v1_bookings__code__patch"];
        trace?: never;
    };
    "/api/v1/bookings/{code}/voucher.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Voucher */
        get: operations["voucher_api_v1_bookings__code__voucher_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{code}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel
         * @description Cancelación del cliente según política; ya cancelada o completada → 409.
         */
        post: operations["cancel_api_v1_bookings__code__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{code}/payments/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment Intent
         * @description Crea o reutiliza el intent de la reserva (F4.2); dos llamadas dan el mismo secreto.
         */
        post: operations["payment_intent_api_v1_bookings__code__payments_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{code}/payments/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment Confirm
         * @description Confirmación rápida verificada con Stripe (F4.3); un intent de otra reserva → 400.
         */
        post: operations["payment_confirm_api_v1_bookings__code__payments_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Contact
         * @description Formulario de contacto. A un bot (honeypot con texto) se le responde igual sin guardar.
         */
        post: operations["contact_api_v1_contact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Firma inválida → 400 (F4.4). Un evento repetido no se procesa dos veces.
         */
        post: operations["stripe_webhook_api_v1_webhooks_stripe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Route
         * @description Contraseña correcta con owner/manager no entrega sesión: exige TOTP (F6.2).
         */
        post: operations["login_route_api_v1_admin_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/totp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Totp Verify Route
         * @description Alta (secreto nuevo en el token) o login normal, según lo que traiga el `challenge_token`.
         */
        post: operations["totp_verify_route_api_v1_admin_auth_totp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Route */
        post: operations["logout_route_api_v1_admin_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me Route */
        get: operations["me_route_api_v1_admin_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityBookingRequest */
        ActivityBookingRequest: {
            customer: components["schemas"]["CustomerIn"];
            /** Notes */
            notes?: string | null;
            attribution?: components["schemas"]["Attribution"];
            /** Accepted Terms Version */
            accepted_terms_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "activity";
            /** Package */
            package: string;
            /** Activities */
            activities: string[];
            /** Guests */
            guests: number;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "es";
        };
        /** ActivityOut */
        ActivityOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: {
                [key: string]: string;
            };
            /** Description */
            description: {
                [key: string]: string;
            };
            /** Duration Minutes */
            duration_minutes: number;
        };
        /** ActivityQuoteRequest */
        ActivityQuoteRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "activity";
            /** Package */
            package: string;
            /** Activities */
            activities: string[];
            /** Guests */
            guests: number;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "es";
        };
        /** AdminMeOut */
        AdminMeOut: {
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /**
         * Attribution
         * @description Origen de la visita (F3.11): UTM y referrer que la web captura al entrar.
         */
        Attribution: {
            /** Utm Source */
            utm_source?: string | null;
            /** Utm Medium */
            utm_medium?: string | null;
            /** Utm Campaign */
            utm_campaign?: string | null;
            /** Utm Term */
            utm_term?: string | null;
            /** Utm Content */
            utm_content?: string | null;
            /** Referrer */
            referrer?: string | null;
        };
        /**
         * AuthOut
         * @description Misma forma para `/login` (roles sin TOTP) y `/totp/verify`.
         */
        AuthOut: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "authenticated" | "totp_required" | "totp_setup_required";
            /** Challenge Token */
            challenge_token?: string | null;
            /** Totp Uri */
            totp_uri?: string | null;
            /** Csrf Token */
            csrf_token?: string | null;
            /** Backup Codes */
            backup_codes?: string[] | null;
        };
        /** BookingChange */
        BookingChange: {
            /** Legs */
            legs?: components["schemas"]["LegChange"][];
            /** Notes */
            notes?: string | null;
        };
        /** BookingCreated */
        BookingCreated: {
            /** Token */
            token: string;
            /** Code */
            code: string;
            status: components["schemas"]["BookingStatus"];
            /** Payment Method */
            payment_method: string | null;
            /** Currency */
            currency: string;
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Discount Cents */
            discount_cents: number;
            /** Tax Cents */
            tax_cents: number;
            /** Total Cents */
            total_cents: number;
            /** Items */
            items: components["schemas"]["BookingItemOut"][];
        };
        /** BookingDetail */
        BookingDetail: {
            /** Code */
            code: string;
            status: components["schemas"]["BookingStatus"];
            /** Payment Method */
            payment_method: string | null;
            /** Currency */
            currency: string;
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Discount Cents */
            discount_cents: number;
            /** Tax Cents */
            tax_cents: number;
            /** Total Cents */
            total_cents: number;
            /** Items */
            items: components["schemas"]["BookingItemOut"][];
            /** Legs */
            legs: components["schemas"]["BookingLegOut"][];
            /** Notes Customer */
            notes_customer: string | null;
        };
        /** BookingItemOut */
        BookingItemOut: {
            item_type: components["schemas"]["ItemType"];
            /** Service Date */
            service_date: string | null;
            /** Description */
            description: string;
            /** Quantity */
            quantity: number;
            /** Unit Price Cents */
            unit_price_cents: number;
            /** Total Cents */
            total_cents: number;
        };
        /** BookingLegOut */
        BookingLegOut: {
            leg_type: components["schemas"]["LegType"];
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Service Time */
            service_time: string | null;
            /** Pickup Time */
            pickup_time: string | null;
            /** Flight Number */
            flight_number: string | null;
            /** Airline */
            airline: string | null;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Pax Adults */
            pax_adults: number;
            /** Pax Children */
            pax_children: number;
        };
        /**
         * BookingStatus
         * @enum {string}
         */
        BookingStatus: "pending_payment" | "offline_hold" | "confirmed" | "paid" | "completed" | "cancelled";
        /**
         * BookingToken
         * @description Token de gestión: va en `Authorization: Bearer` para ver o cambiar la reserva.
         */
        BookingToken: {
            /** Token */
            token: string;
        };
        /** CancelRequest */
        CancelRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** ContactIn */
        ContactIn: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Message */
            message: string;
            /** Source Page */
            source_page?: string | null;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "es";
            /** Website */
            website?: string | null;
            /** Turnstile Token */
            turnstile_token?: string | null;
        };
        /** ContactReceived */
        ContactReceived: {
            /**
             * Status
             * @default received
             * @constant
             */
            status: "received";
        };
        /** CustomerIn */
        CustomerIn: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Confirm Email
             * Format: email
             */
            confirm_email: string;
            /** Phone */
            phone: string;
            /** Country */
            country?: string | null;
            /**
             * Marketing Opt In
             * @default false
             */
            marketing_opt_in: boolean;
        };
        /** ExtraIn */
        ExtraIn: {
            /** Code */
            code: string;
            /** Quantity */
            quantity: number;
        };
        /** ExtraOut */
        ExtraOut: {
            /** Code */
            code: string;
            /** Name */
            name: {
                [key: string]: string;
            };
            /** Description */
            description: {
                [key: string]: string;
            };
            /** Price Cents */
            price_cents: number;
            pricing_mode: components["schemas"]["PricingMode"];
            /** Max Qty */
            max_qty: number;
            /** Included */
            included: boolean;
            /** Free Qty */
            free_qty: number;
            /** Vehicle Prices */
            vehicle_prices: {
                [key: string]: number;
            };
            /** One Per Vehicle */
            one_per_vehicle: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HotelMatch */
        HotelMatch: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Zone */
            zone: string;
            /** Zone Name */
            zone_name: {
                [key: string]: string;
            };
        };
        /** HotelPage */
        HotelPage: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            zone: components["schemas"]["ZoneOut"];
            /** Rates */
            rates: components["schemas"]["RateOut"][];
        };
        /**
         * ItemType
         * @enum {string}
         */
        ItemType: "transfer" | "extra" | "activity" | "park_fee" | "discount";
        /** LegChange */
        LegChange: {
            leg_type: components["schemas"]["LegType"];
            /** Service Time */
            service_time?: string | null;
            /** Flight Number */
            flight_number?: string | null;
            /** Airline */
            airline?: string | null;
        };
        /** LegIn */
        LegIn: {
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Service Time */
            service_time?: string | null;
            /** Flight Number */
            flight_number?: string | null;
            /** Airline */
            airline?: string | null;
            /**
             * International
             * @default true
             */
            international: boolean;
            /** Pickup Time */
            pickup_time?: string | null;
        };
        /**
         * LegType
         * @enum {string}
         */
        LegType: "arrival" | "departure" | "local";
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PackageOut */
        PackageOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: {
                [key: string]: string;
            };
            /** Activity Count */
            activity_count: number;
            /** Price Per Person Cents */
            price_per_person_cents: number;
            /** Park Fee Cents */
            park_fee_cents: number;
            /** Deposit Cents */
            deposit_cents: number;
        };
        /** PaymentConfirmIn */
        PaymentConfirmIn: {
            /** Payment Intent Id */
            payment_intent_id: string;
        };
        /**
         * PaymentIntentOut
         * @description Va al Payment Element de Stripe en el navegador; no es sensible por sí solo.
         */
        PaymentIntentOut: {
            /** Client Secret */
            client_secret: string;
        };
        /**
         * PricingMode
         * @enum {string}
         */
        PricingMode: "per_booking" | "per_stop" | "per_seat" | "per_hour";
        /** Quote */
        Quote: {
            /** Currency */
            currency: string;
            /** Lines */
            lines: components["schemas"]["QuoteLine"][];
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Discount Cents */
            discount_cents: number;
            /** Tax Cents */
            tax_cents: number;
            /** Total Cents */
            total_cents: number;
            /** Vehicle Class */
            vehicle_class?: string | null;
            /**
             * Vehicle Count
             * @default 1
             */
            vehicle_count: number;
            /** Zone */
            zone?: string | null;
            /** Promotion */
            promotion?: string | null;
            /**
             * Due On Site Cents
             * @default 0
             */
            due_on_site_cents: number;
            /**
             * Deposit Cents
             * @default 0
             */
            deposit_cents: number;
        };
        /** QuoteLine */
        QuoteLine: {
            kind: components["schemas"]["ItemType"];
            /** Code */
            code: string | null;
            /** Description */
            description: string;
            /** Quantity */
            quantity: number;
            /** Unit Price Cents */
            unit_price_cents: number;
            /** Total Cents */
            total_cents: number;
        };
        /** RateOut */
        RateOut: {
            /** Vehicle Class */
            vehicle_class: string;
            trip_type: components["schemas"]["TripType"];
            service_scope: components["schemas"]["ServiceScope"];
            /** Price Cents */
            price_cents: number;
        };
        /**
         * ServiceScope
         * @enum {string}
         */
        ServiceScope: "airport" | "local";
        /** TotpVerifyIn */
        TotpVerifyIn: {
            /** Challenge Token */
            challenge_token: string;
            /** Code */
            code: string;
        };
        /** TransferBookingRequest */
        TransferBookingRequest: {
            customer: components["schemas"]["CustomerIn"];
            /** Notes */
            notes?: string | null;
            attribution?: components["schemas"]["Attribution"];
            /** Accepted Terms Version */
            accepted_terms_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "transfer";
            /**
             * Hotel Id
             * Format: uuid
             */
            hotel_id: string;
            trip_type: components["schemas"]["TripType"];
            /** @default airport */
            service_scope: components["schemas"]["ServiceScope"];
            /** Passengers */
            passengers: number;
            /**
             * Direction
             * @default arrival
             * @enum {string}
             */
            direction: "arrival" | "departure";
            /**
             * Payment
             * @default card
             * @enum {string}
             */
            payment: "card" | "cash";
            /** Vehicle Class */
            vehicle_class?: string | null;
            /** Legs */
            legs: components["schemas"]["LegIn"][];
            /** Extras */
            extras?: components["schemas"]["ExtraIn"][];
            /** Promo Code */
            promo_code?: string | null;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "es";
        };
        /** TransferQuoteRequest */
        TransferQuoteRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "transfer";
            /**
             * Hotel Id
             * Format: uuid
             */
            hotel_id: string;
            trip_type: components["schemas"]["TripType"];
            /** @default airport */
            service_scope: components["schemas"]["ServiceScope"];
            /** Passengers */
            passengers: number;
            /**
             * Direction
             * @default arrival
             * @enum {string}
             */
            direction: "arrival" | "departure";
            /**
             * Payment
             * @default card
             * @enum {string}
             */
            payment: "card" | "cash";
            /** Vehicle Class */
            vehicle_class?: string | null;
            /** Legs */
            legs: components["schemas"]["LegIn"][];
            /** Extras */
            extras?: components["schemas"]["ExtraIn"][];
            /** Promo Code */
            promo_code?: string | null;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "es";
        };
        /**
         * TripType
         * @enum {string}
         */
        TripType: "one_way" | "round_trip";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VehicleOut */
        VehicleOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Min Pax */
            min_pax: number;
            /** Max Pax */
            max_pax: number;
            /** Max Bags */
            max_bags: number;
            /** Included Pax */
            included_pax: number | null;
            /** Extra Pax Cents */
            extra_pax_cents: number;
            /** Extra Hour Cents */
            extra_hour_cents: number;
            /** Cash Deposit Cents */
            cash_deposit_cents: number;
        };
        /** ZoneOut */
        ZoneOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: {
                [key: string]: string;
            };
            /** Drive Minutes Min */
            drive_minutes_min: number;
            /** Drive Minutes Max */
            drive_minutes_max: number;
            /** From Price Cents */
            from_price_cents?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    zones_api_v1_catalog_zones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneOut"][];
                };
            };
        };
    };
    hotels_api_v1_catalog_hotels_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelMatch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hotel_api_v1_catalog_hotels__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vehicles_api_v1_catalog_vehicles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleOut"][];
                };
            };
        };
    };
    extras_api_v1_catalog_extras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtraOut"][];
                };
            };
        };
    };
    activities_api_v1_catalog_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"][];
                };
            };
        };
    };
    packages_api_v1_catalog_packages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"][];
                };
            };
        };
    };
    create_quote_api_v1_quotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferQuoteRequest"] | components["schemas"]["ActivityQuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_bookings_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferBookingRequest"] | components["schemas"]["ActivityBookingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_api_v1_bookings_lookup_get: {
        parameters: {
            query: {
                code: string;
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingToken"];
                };
            };
            /** @description Booking not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_v1_bookings__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_api_v1_bookings__code__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voucher_api_v1_bookings__code__voucher_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_bookings__code__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    payment_intent_api_v1_bookings__code__payments_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    payment_confirm_api_v1_bookings__code__payments_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contact_api_v1_contact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactReceived"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_api_v1_webhooks_stripe_post: {
        parameters: {
            query?: never;
            header: {
                "stripe-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_route_api_v1_admin_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    totp_verify_route_api_v1_admin_auth_totp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpVerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_route_api_v1_admin_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_route_api_v1_admin_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMeOut"];
                };
            };
        };
    };
}
